### ISSUE TITLE
Depending on the format of the header, ID extraction might show undefined ID names

### ISSUE THREAD

**Issue by jotasolano** [NX4/nx4#11]
This problem occurs because different people use different header conventions for their FASTAs. It is probably impossible to satisfy every single case, but we can think of a way to fix this for most cases.

The original files we were working with (EBOV and MuV) have a header like so:

`>Ebola_virus_H.sapiens_wt/GBR/2015/Makona_UK3|KR025228|United_Kingdom|2015_03_12`

We adapted the parser in order to get a better ID, because by default, the parser will get a `name` key using the string right after the last `|` symbol in the header, which in this case would be `2015_03_12`.

However, the UniProt standard for instance, reinforces the use of that last string for the name, and not for a date: (https://www.uniprot.org/help/fasta-headers)

`>db|UniqueIdentifier|EntryName`

The NCBI Standard, which is also widely used, does not comment on the use of `|`, instead, it requires that there be no blank spaces in the header, but it does not specify any format like UniProt. (https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp)

So, my suggestion is, to make things a little flexible, but also not too flexible, we can use some conditionals in the parser, to **reconstruct the header if it follows the UniProt standard, and otherwise, try to do as better as possible.**

I wrote a little script to demonstrate this with 4 different headers: https://stackblitz.com/edit/biojs-fasta-parser-ex?file=index.js

What does the script do? Looking again at the UniProt standard `>db|UniqueIdentifier|EntryName`, the script attempts to extract `db`, `UniqueIdentifier` and `EntryName`. If `db` or `UniqueIdentifier` are missing, we only show `EntryName`.

This way we can control for cases that have only one string of text, like in the new dataset we're using, or for when the header only has two strings (eg. `>something|somethingElse`). As you can see in StackBlitz, for a header like `>Ebola_virus_H.sapiens_wt/GBR/2015/Makona_UK3|KR025228|United_Kingdom|2015_03_12` the best we can do is `Ebola_virus_H.sapiens_wt/GBR/2015/Makona_UK3|KR025228|2015_03_12` (we drop "United_Kingdom"), as we would have to control for additional terms.

How does this sound?

**Comment by carcruz** [comment]
Great! The stackbiltz worked perfect. Fix add to master and deployed to production.
