### ISSUE TITLE
Add filename to navbar after loading

### ISSUE THREAD

**Issue by jotasolano** [NX4/nx4#12]
Take the filename and add it as text to the nav bar once the alignment has successfully loaded

**Comment by jotasolano** [comment]
@carcruz

**Comment by carcruz** [comment]
Add feature in commit [fdf5448b638dd23efc7fdb099959bc6ce7621155](https://github.com/NX4/nx4/commit/fdf5448b638dd23efc7fdb099959bc6ce7621155)
