### ISSUE TITLE
Side panel display when selecting a position

### ISSUE THREAD

**Issue by jotasolano** [NX4/nx4#13]
Current:
Panel for download displays under the main viz

Expected:
Panel displays on the right side
The clicked rectangle is highlighted to show which position is being selected

**Comment by jotasolano** [comment]
@carcruz

**Comment by carcruz** [comment]
Add it in [0dcaf4b4bc25d14d78dfdfa0538c5d7afc7b8e9a]( https://github.com/NX4/nx4/commit/0dcaf4b4bc25d14d78dfdfa0538c5d7afc7b8e9a)
